#!/bin/bash
# genproj

dir=$(dirname $(dirname $(realpath $0)))

project() {
    proj=$1; type=$2; main=$3; targ=$4; name=${proj%%-*}
    sed -e "s:@PROJNAME@:$name:" \
        -e "s:@TARGET@:$targ:" \
        -e "s:@PROJDIR@:$dir/$proj:" \
        -e "s:@MICROBIAN@:$dir/microbian:" \
        -e "s:@MAINFILE@:$dir/$proj/$main:" \
        -e "/^FILE_NAME/s:/:%2F:g" \
        $dir/setup/$type.geany >$dir/$proj/$name.geany
}

project 01 part2 echo.c echo.hex
project 02 part1 func.s func.hex
project 03 part1 max.s max.hex
project 04 part1 mult.s mult.hex
project 05 part1 fact.s fact.hex
project 06 part1 bank.s bank.hex
project 07 hack total.c total.hex
project 08 part2 heart.c heart.hex
project 09 pureasm blinky.s blinky.hex
project 10 part2 primes.c primes.hex
project 11 part2 primes2.c primes2.hex
project 12 part2 bitbang.c bitbang.hex
project 13 part2 rainbow.c rainbow.hex
project 14 part3 valentine.c valentine.hex
project 15 part3 pcount.c pcount.hex
project 16 part3 chaos.c chaos.hex
project 17 part3 myprimes.c myprimes.hex
project 18 part3 level.c level.hex
project 19 part3 buggy.c buggy.hex
project 20 part3 remote.c remote.hex
project 21 part3 car.c car.hex
