#!/bin/bash
# genproj

dir=$(dirname $(dirname $(realpath $0)))

project() {
    proj=$1; type=$2; main=$3; targ=$4; name=${proj%%-*}
    sed -e "s:@PROJNAME@:$name:" \
        -e "s:@TARGET@:$targ:" \
        -e "s:@PROJDIR@:$dir/$proj:" \
        -e "s:@MICROBIAN@:$dir/microbian:" \
        -e "s:@MAINFILE@:$dir/$proj/$main:" \
        -e "/^FILE_NAME/s:/:%2F:g" \
        $dir/setup/$type.geany >$dir/$proj/$name.geany
}

project x1000-echo part2 echo.c echo.hex
project x1100-instrs part1 func.s func.hex
project x1200-loops part1 mult.s mult.hex
project x1300-subrs part1 fact.s fact.hex
project x1400-arrays part1 bank.s bank.hex
project x1500-hack hack total.c total.hex
project x2000-heart part2 heart.c heart.hex
project x2040-pureasm part1 blinky.s blinky.hex
project x2100-serial part2 primes.c primes.hex
project x2200-interrupt part2 primes2.c primes2.hex
project x2300-intrmech part2 bitbang.c bitbang.hex
project x2400-neopixels part2 rainbow.c rainbow.hex
project x3000-processes part3 valentine.c valentine.hex
project x3040-messages part3 pcount.c pcount.hex
project x3100-sync part3 chaos.c chaos.hex
project x3200-driver part3 myprimes.c myprimes.hex
project x3300-level part3 level.c level.hex
project x3500-servos part3 buggy.c buggy.hex
project x3600-radio part3 remote.c remote.hex
project x3700-car part3 car.c car.hex
